# Generated by Django 2.1 on 2018-11-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objectstorage',
            new_name='ObjectstorageGeneral',
        ),
    ]
