# Generated by Django 2.1 on 2018-11-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0004_objectstorageinterface'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectstorageScalability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3', models.CharField(max_length=64, null=True)),
                ('swift', models.CharField(max_length=64, null=True)),
                ('nfs', models.CharField(max_length=64, null=True)),
                ('cifs', models.CharField(max_length=64, null=True)),
                ('hdfs', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='objectstoragegeneral',
            name='deployment_option',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='objectstoragegeneral',
            name='release_date',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='objectstoragegeneral',
            name='software_version',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='objectstoragescalability',
            name='product_id',
            field=models.ForeignKey(on_delete=None, to='storagematrix.ObjectstorageGeneral'),
        ),
    ]
