# Generated by Django 2.1 on 2018-11-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0006_objectstoragedataavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectstorageDataService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe', models.CharField(max_length=64, null=True)),
                ('compression', models.CharField(max_length=64, null=True)),
                ('tiering_to_cloud', models.CharField(max_length=64, null=True)),
                ('autotiering', models.CharField(max_length=64, null=True)),
                ('worm', models.CharField(max_length=64, null=True)),
                ('versioning', models.CharField(max_length=64, null=True)),
                ('metadatasearch', models.CharField(max_length=64, null=True)),
                ('product_id', models.ForeignKey(on_delete=None, to='storagematrix.ObjectstorageGeneral')),
            ],
        ),
    ]
