# Generated by Django 2.1 on 2018-11-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0008_auto_20181122_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectstoragedataavailability',
            old_name='cifs',
            new_name='multi_sites',
        ),
        migrations.RemoveField(
            model_name='objectstoragedataavailability',
            name='hdfs',
        ),
        migrations.RemoveField(
            model_name='objectstoragedataavailability',
            name='nfs',
        ),
        migrations.RemoveField(
            model_name='objectstoragedataavailability',
            name='swift',
        ),
        migrations.AddField(
            model_name='objectstoragegeneral',
            name='node_type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
