# Generated by Django 2.1 on 2018-11-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0009_auto_20181122_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectstorageAccessSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl', models.CharField(max_length=64, null=True)),
                ('bucket_policy', models.CharField(max_length=64, null=True)),
                ('user_policy', models.CharField(max_length=64, null=True)),
                ('product_id', models.ForeignKey(on_delete=None, to='storagematrix.ObjectstorageGeneral')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectstorageEcosystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isilon', models.CharField(max_length=64, null=True)),
                ('datadomain', models.CharField(max_length=64, null=True)),
                ('nbu', models.CharField(max_length=64, null=True)),
                ('product_id', models.ForeignKey(on_delete=None, to='storagematrix.ObjectstorageGeneral')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectstorageHardwareSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.TextField(null=True)),
                ('memory', models.TextField(null=True)),
                ('disk', models.TextField(null=True)),
                ('network', models.TextField(null=True)),
                ('product_id', models.ForeignKey(on_delete=None, to='storagematrix.ObjectstorageGeneral')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectstorageOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_procedure', models.CharField(max_length=64, null=True)),
                ('performance_monitoring', models.CharField(max_length=64, null=True)),
                ('capacity_monitoring', models.CharField(max_length=64, null=True)),
                ('alert', models.CharField(max_length=64, null=True)),
                ('audit_log', models.CharField(max_length=64, null=True)),
                ('data_access_log', models.CharField(max_length=64, null=True)),
                ('product_id', models.ForeignKey(on_delete=None, to='storagematrix.ObjectstorageGeneral')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.TextField(null=True)),
                ('memory', models.TextField(null=True)),
                ('disk', models.TextField(null=True)),
                ('network', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='objectstoragedataavailability',
            old_name='multi_sites',
            new_name='disk_failure',
        ),
        migrations.AddField(
            model_name='objectstoragedataavailability',
            name='node_failure',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='objectstoragedataavailability',
            name='rack_failure',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='objectstoragedataavailability',
            name='site_failure',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='objectstoragedataservice',
            name='access_load_balance',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='objectstoragedataservice',
            name='cross_interface_access',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='objectstoragedataservice',
            name='multi_sites',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='objectstoragedataservice',
            name='multi_sites_distribution',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
