# Generated by Django 2.1 on 2018-11-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0010_auto_20181123_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='network',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
