# Generated by Django 2.1 on 2018-11-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0012_auto_20181123_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
