# Generated by Django 2.1 on 2018-12-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0014_auto_20181203_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectstorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, unique=True)),
                ('vendor', models.CharField(max_length=64, null=True)),
                ('software_version', models.CharField(max_length=64, null=True)),
                ('release_date', models.CharField(max_length=64, null=True)),
                ('deployment_option', models.CharField(max_length=64, null=True)),
                ('node_type', models.CharField(max_length=64, null=True)),
                ('s3', models.CharField(max_length=64, null=True)),
                ('swift', models.CharField(max_length=64, null=True)),
                ('nfs', models.CharField(max_length=64, null=True)),
                ('cifs', models.CharField(max_length=64, null=True)),
                ('hdfs', models.CharField(max_length=64, null=True)),
                ('max_capacity_per_cluster', models.CharField(max_length=64, null=True)),
                ('max_nodes_per_cluster', models.CharField(max_length=64, null=True)),
                ('max_buckets_per_cluster', models.CharField(max_length=64, null=True)),
                ('max_objects_per_cluster', models.CharField(max_length=64, null=True)),
                ('max_capacity_per_bucket', models.CharField(max_length=64, null=True)),
                ('max_objects_per_bucket', models.CharField(max_length=64, null=True)),
                ('max_objects_per_node', models.CharField(max_length=64, null=True)),
                ('erasure_code', models.CharField(max_length=64, null=True)),
                ('multi_copy', models.CharField(max_length=64, null=True)),
                ('disk_failure', models.CharField(max_length=64, null=True)),
                ('node_failure', models.CharField(max_length=64, null=True)),
                ('rack_failure', models.CharField(max_length=64, null=True)),
                ('site_failure', models.CharField(max_length=64, null=True)),
                ('dedupe', models.CharField(max_length=64, null=True)),
                ('compression', models.CharField(max_length=64, null=True)),
                ('tiering_to_cloud', models.CharField(max_length=64, null=True)),
                ('autotiering', models.CharField(max_length=64, null=True)),
                ('worm', models.CharField(max_length=64, null=True)),
                ('versioning', models.CharField(max_length=64, null=True)),
                ('metadatasearch', models.CharField(max_length=64, null=True)),
                ('multi_sites_access', models.CharField(max_length=64, null=True)),
                ('cross_interface_access', models.CharField(max_length=64, null=True)),
                ('multi_sites_distribution', models.CharField(max_length=64, null=True)),
                ('access_load_balance', models.CharField(max_length=64, null=True)),
                ('acl', models.CharField(max_length=64, null=True)),
                ('bucket_policy', models.CharField(max_length=64, null=True)),
                ('user_policy', models.CharField(max_length=64, null=True)),
                ('installation_procedure', models.CharField(max_length=64, null=True)),
                ('performance_monitoring', models.CharField(max_length=64, null=True)),
                ('capacity_monitoring', models.CharField(max_length=64, null=True)),
                ('alert', models.CharField(max_length=64, null=True)),
                ('audit_log', models.CharField(max_length=64, null=True)),
                ('data_access_log', models.CharField(max_length=64, null=True)),
                ('cpu', models.TextField(null=True)),
                ('memory', models.TextField(null=True)),
                ('disk', models.TextField(null=True)),
                ('network', models.TextField(null=True)),
                ('isilon', models.CharField(max_length=64, null=True)),
                ('datadomain', models.CharField(max_length=64, null=True)),
                ('nbu', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='objectstorageaccesssecurity',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='objectstoragedataavailability',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='objectstoragedataservice',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='objectstorageecosystem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='objectstoragehardwarespec',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='objectstorageinterface',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='objectstorageoperation',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='objectstoragescalability',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='ObjectstorageAccessSecurity',
        ),
        migrations.DeleteModel(
            name='ObjectstorageDataAvailability',
        ),
        migrations.DeleteModel(
            name='ObjectstorageDataService',
        ),
        migrations.DeleteModel(
            name='ObjectstorageEcosystem',
        ),
        migrations.DeleteModel(
            name='ObjectstorageGeneral',
        ),
        migrations.DeleteModel(
            name='ObjectstorageHardwareSpec',
        ),
        migrations.DeleteModel(
            name='ObjectstorageInterface',
        ),
        migrations.DeleteModel(
            name='ObjectstorageOperation',
        ),
        migrations.DeleteModel(
            name='ObjectstorageScalability',
        ),
    ]
