# Generated by Django 2.1 on 2018-12-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0015_auto_20181204_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectstorage',
            old_name='nbu',
            new_name='netbackup',
        ),
    ]
