# Generated by Django 2.1 on 2018-12-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagematrix', '0016_auto_20181216_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectstorage',
            name='enterprisevault',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
