# Generated by Django 2.1 on 2018-08-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_content', models.TextField()),
                ('next_step', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=64, unique=True)),
                ('ase', models.CharField(max_length=64, unique=True)),
                ('ase_manager', models.CharField(max_length=64, unique=True)),
                ('dcse', models.CharField(max_length=64, unique=True)),
                ('dcse_manager', models.CharField(max_length=64, unique=True)),
                ('uds_sales', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=64, unique=True)),
                ('target_date', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(max_length=64, unique=True)),
                ('customer_id', models.ForeignKey(on_delete=None, to='projecttracking.Customers')),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='customer_id',
            field=models.ForeignKey(on_delete=None, to='projecttracking.Customers'),
        ),
        migrations.AddField(
            model_name='activities',
            name='project_id',
            field=models.ForeignKey(on_delete=None, to='projecttracking.Projects'),
        ),
    ]
