# Generated by Django 2.1 on 2018-08-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecttracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ase',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ase_manager',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='dcse',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='dcse_manager',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='uds_sales',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='target_date',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
