# Generated by Django 2.1 on 2018-08-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecttracking', '0002_auto_20180815_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='project_status',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
