# Generated by Django 2.1 on 2018-08-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecttracking', '0003_activities_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.CharField(max_length=64),
        ),
    ]
