# Generated by Django 2.1 on 2018-08-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecttracking', '0008_auto_20180816_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='revenue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='solution',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='next_step',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
