# Generated by Django 2.1 on 2018-08-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecttracking', '0010_auto_20180816_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='update_date',
            field=models.DateField(null=True),
        ),
    ]
