# Generated by Django 2.1 on 2018-08-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecttracking', '0011_auto_20180816_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
