# Generated by Django 2.1 on 2018-08-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecttracking', '0012_auto_20180816_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
