# Generated by Django 2.1 on 2018-08-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecttracking', '0014_auto_20180818_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='sales_division',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='sales_team',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
